spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events_db?useSSl=false&allowPublicKeyRetrieval=true&serverTimeZone=IST
    username: event_user
    password: events_pass
    hikari:
      maximum-pool-size: 5
  
logging:
  level:
    org.springframework.jdbc.SQL: DEBUG
    com.sudhanshu.eventservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: DEBUG

server:
  port: ${PORT:0}

resilience4j:
  circuitbreaker:
    instances:
      dbService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  timelimiter:
    instances:
      dbService:
        timeout-duration: 3s

  retry:
    instances:
      dbService:
        max-attempts: 2
        wait-duration: 200ms
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
      base-path: /actuator  # Default
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
