server:
  port: 8065
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EVENT-SERVICE
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=0
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/user-profiles/**
        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/reports/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: auth-server
            client-id: gateway-client
            client-secret: gateway-secret
            authorization-grant-type: client_credentials
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks
        provider:
          auth-server:
            token-uri: http://localhost:9000/oauth2/token
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      appName: gateway-service
      preferIpAddress: true
      instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,gateway,routes,mappings,loggers
  endpoint:
    health:
      show-details: always
      enabled: true
    gateway:
      enabled: true  # Gateway Actuator ONLY
    shutdown:
      enabled: false
  info:
    git:
      mode: simple
    env:
      enabled: true

