spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/profiles_db?useSSl=false&allowPublicKeyRetrieval=true&serverTimeZone=IST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_profiles_user
    password: user_profiles_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:0}

eureka:
  client:
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appName: profile-service
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: ${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes,refresh
      base-path: /actuator  # Default
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
info:
  env:
    enabled: true
  git:
    mode: simple